frontend/controllers/FilmController.php
<?php
/**
 * Created by PhpStorm.
 * User: pavel
 * Date: 16.07.18
 * Time: 10:44
 */

/* @var $films common\models\Film[] */

namespace frontend\controllers;


use common\models\Film;
use yii\web\Controller;
use yii\data\Pagination;

class FilmController extends Controller
{
    public function actionShow()
    {
        $films = Film::find()->all();

        return $this->render('show', compact('films'));
    }

    /**
     * @return string
     */
    public function actionAllFilms()
    {
        $films = Film::find();


        $pagination = new Pagination([
            'defaultPageSize' => 12,
            'totalCount' => $films->count()
        ]);
        $films = $films->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('allFilms', [
            'films' => $films,
            'pagination' => $pagination
        ]);
    }

    public function actionInfoFilm($id)
    {
        $film = Film::find()->where(['id'=> $id])->limit(1)->one();

        return $this->render('infoFilm', compact('film'));
    }



}

frontend/controllers/PosterController.php
<?php
/**
 * Created by PhpStorm.
 * User: pavel
 * Date: 16.07.18
 * Time: 11:03
 */

namespace frontend\controllers;


use yii\db\Query;
use yii\web\Controller;
use common\models\Film;
use yii\data\Pagination;

class PosterController extends Controller
{
    /**
     * @return string
     * @throws \yii\db\Exception
     */


    public function actionShow()
    {
        $time = new \DateTime('now');
        $today = $time->format('Y-m-d');

        $films_new = Film::find()
            ->joinWith('timings')
            ->where(['is not', 'film_id', null])
            ->andWhere(['>', 'start_show', $today])
            ->orderBy(['start_show' => SORT_DESC])
            ->groupBy('`film`.`id`');

        $pagination_new = new Pagination([
            'defaultPageSize' => 6,
            'totalCount' => $films_new->count()
        ]);

        $films_new = $films_new->offset($pagination_new->offset)
            ->limit($pagination_new->limit)
            ->all();


        $films_now = Film::find()
            ->joinWith('timings')
            ->where(['is not', 'film_id', null])
            ->andWhere(['<=', 'start_show', $today])
            ->orderBy(['start_show' => SORT_DESC])
            ->groupBy('`film`.`id`');

        $pagination_now = new Pagination([
            'defaultPageSize' => 6,
            'totalCount' => $films_now->count()
        ]);

        $films_now = $films_now->offset($pagination_now->offset)
            ->limit($pagination_now->limit)
            ->all();




        return $this->render('show', [
            'films_new' => $films_new,
            'films_now' => $films_now,
            'pagination_new' => $pagination_new,
            'pagination_old' => $pagination_now
        ]);
    }

    public function actionInfoFilm($id)
    {
        $film = Film::find()->where(['id'=> $id])->limit(1)->one();

        return $this->render('infoFilm', compact('film'));
    }




}

frontend/views/poster/infoFilm.php
<?php
/* @var $film common\models\Film */
?>

<iframe width="1140" height="630"
        src="<?= $film->trailer_link ?>" frameborder="0" allowfullscreen>
</iframe>

<?php if(!empty($film->timings)): ?>
<div class="panel panel-default">

    <div class="panel-heading"><h1>Расписание</h1></div>

    <table class="table table-bordered table-dark">
        <thead>
        <tr>
            <th scope="col">Кинотеатр</th>
            <th scope="col">Дата и время</th>
            <th scope="col">Зал</th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($film->getTimings()->orderBy(['date_show' => SORT_ASC])->all() as $timing): ?>
            <tr>
                <td><?= $timing->hall->cinema->title ?></td>
                <td><?= $timing->date_show ?></td>
                <td><?= $timing->hall->title ?></td>

            </tr>
        <?php endforeach; ?>

        </tbody>
    </table>
</div>
<?php else:  ?>
    <div align="center">
        <h1> Показ завершен</h1>
    </div>
<?php endif; ?>

<div align="center">
    <img src=" <?='/resource/img/films/' . $film->picture ?> " width="567" height="765" >
    <h2><?=$film->title ?></h2>
    <h2 ><?=$film->showAge() ?></h2>
    <p><button type="button" class="btn btn-success"><h3>Купить билет</h3></button></p>

    <div class="jumbotron">
        <h3>Описание</h3>
        <p><?= $film->description ?></p>

    </div>

    <table class="table table-bordered">
        <tbody>
        <tr>
            <td>Жанр</td>
            <td>
                <?= $film->showGenres(); ?>
            </td>
        </tr>
        <tr>
            <td>Год</td>
            <td><?=$film->year ?></td>
        </tr>
        <tr>
            <td>Старт показа</td>
            <td><?=$film->start_show ?></td>
        </tr>
         <tr>
            <td>Страна</td>
            <td><?=$film->country ?></td>
        </tr>
         <tr>
            <td>Компания</td>
            <td><?=$film->company ?></td>
        </tr>
        <tr>
            <td>Продюсер</td>
            <td><?=$film->showProducer() ?></td>
        </tr>
        <tr>
            <td>Бюджет</td>
            <td><?=$film->showBudget() ?></td>
        </tr>

        </tbody>
    </table>

</div>

<pre>
    <?= var_dump($film->timings) ?>
    <?= print_r($film->filmGenres)?>
</pre>

frontend/views/poster/show.php
<?php

/* @var $films_new common\models\Film[] */
/* @var $films_now common\models\Film[] */

use yii\widgets\LinkPager;
use yii\helpers\Url;

?>



<div class="body-content">

    <div class="row" align="center">

        <h1>Ожидаемые фильмы</h1>

        <?php foreach ($films_new as $film): ?>

            <div class="col-lg-4">
                <h2><?= $film->title ?></h2>
                <h4><?= $film->showAge() ?></h4>
                <h4><?= $film->showStartShow() ?></h4>
                <img src="<?='/resource/img/films/' . $film->picture ?>" width="189" height="255">
               <!-- <p><a class="btn btn-default" href="info-film?id=<?/*= $film->id */?>">Подробно</a></p>
                <p><a class="btn btn-default" href="<?/*= Yii::$app->urlManager->createUrl(['film/info-film', 'id' => $film->id]) */?>">Подробно</a></p>
               -->
                <p><a class="btn btn-default" href="<?= Url::to(['film/info-film', 'id' => 5]) ?>">Подробно</a></p>
            </div>

        <?php endforeach; ?>

    </div>
</div>

    <div class="body-content">

        <div class="row" align="center">

            <h1>Смотрите сейчас</h1>

            <?php foreach ($films_now as $film): ?>

                <div class="col-lg-4">
                    <h2><?= $film->title ?></h2>
                    <h4><?= $film->showAge() ?></h4>
                    <h4><?= $film->showStartShow() ?></h4>
                    <img src="<?='/resource/img/films/' . $film->picture ?>" width="189" height="255">
                    <p><a class="btn btn-default" href="info-film?id=<?= $film->id ?>">Подробно</a></p>
                </div>

            <?php endforeach; ?>

        </div>

    </div>